### ISSUE TITLE
HiD.lib not found

### ISSUE THREAD

**Issue by RyanDavisGamesLLC** [KITATUS/DualSenseWindows_UE4#1]
I'm very excited you wrapped this in a plugin. Thanks for getting this started! 

When trying to open in Unreal I got a compile error. I took a look at the logs and then the build.cs file and it looks like this plugin is looking for 'C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17134.0\um\x64\hid.lib', which is not a directory or file my computer has. After some Googling that appears to be a USB communication driver library from Windows, am I right? Do you have any recommendations for getting this file? Is this a bug in the plugin that needs to be fixed? Any help would be greatly appreciated.

**Comment by mwnDK1402** [comment]
Problem for me was that it was a different version:
`C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\x64\hid.lib`
